In [26]:
import numpy as np
from numpy.linalg import inv

In [79]:
t2 = [0.729,0.3106,0.5739,0.2348,0.2521,0.2656,0.2009,0.2117,0.2027,0.2376,0.1784,0.2757,0.2216,0.2194,0.2669,0.202,0.2129,0.2131,0.2135,0.2017,0.2362,0.2326,0.2503]

In [80]:
t3 = [-0.0536,-0.1257,-0.0326,0.4026,0.3706,0.2087,0.2278,0.2511,0.1611,0.0358,0.1017,0.2962,0.0446,0.1292,0.2544,0.1111,0.1996,0.1414,0.1362,0.1605,0.2075,0.1673,0.144]

In [87]:
t4 = [0.0542,0.1969,0.16,0.1866,0.2048,0.0098,0.1985,0.2001,0.0018,0.0216,0.0218,0.1444,0.0567,0.0253,0.0898,0.0631,0.0543,0.1078,0.0842,0.0999,0.0915,0.115,0.0856]

In [88]:
sites = [21,23,22,2,13,12,8,16,7,20,5,10,3,6,14,1,4,19,18,15,17,9,11]

In [89]:
len(sites), len(t2), len(t3), len(t4)

(23, 23, 23, 23)

In [37]:

#lmrs <- t(matrix(c(t2, t3, t4), ncol=3))

lmrs = np.column_stack((t2, t3, t4))

In [48]:
Dcr_table_31 =np.array([1.3333, 1.6481, 1.9166, 2.1401, 2.3287,
                       2.4906, 2.6321, 2.7573, 2.8694, 2.9709, 3.])

In [39]:
# lmrmeans is Hosking and Wallis (1997, eq. 3.1)
#  lmrmeans <- sapply(1:3, function(i) { mean(lmrs[i, ])        })

lmrmeans = lmrs.mean(0)
lmrmeans

array([0.26709565, 0.1538913 , 0.09885652])

In [40]:
#tmp <- sapply(1:3, function(i) { lmrs[i,] - lmrmeans[i] })
# ui - ubar
tmp = np.subtract(lmrs,lmrmeans)
tmp

array([[ 4.61904348e-01, -2.07491304e-01, -4.46565217e-02],
       [ 4.35043478e-02, -2.79591304e-01,  9.80434783e-02],
       [ 3.06804348e-01, -1.86491304e-01,  6.11434783e-02],
       [-3.22956522e-02,  2.48708696e-01,  8.77434783e-02],
       [-1.49956522e-02,  2.16708696e-01,  1.05943478e-01],
       [-1.49565217e-03,  5.48086957e-02, -8.90565217e-02],
       [-6.61956522e-02,  7.39086957e-02,  9.96434783e-02],
       [-5.53956522e-02,  9.72086957e-02,  1.01243478e-01],
       [-6.43956522e-02,  7.20869565e-03, -9.70565217e-02],
       [-2.94956522e-02, -1.18091304e-01, -7.72565217e-02],
       [-8.86956522e-02, -5.21913043e-02, -7.70565217e-02],
       [ 8.60434783e-03,  1.42308696e-01,  4.55434783e-02],
       [-4.54956522e-02, -1.09291304e-01, -4.21565217e-02],
       [-4.76956522e-02, -2.46913043e-02, -7.35565217e-02],
       [-1.95652174e-04,  1.00508696e-01, -9.05652174e-03],
       [-6.50956522e-02, -4.27913043e-02, -3.57565217e-02],
       [-5.41956522e-02,  4.57086957e-02

In [41]:
A = np.zeros((3,3))
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
for j in range(0,3):
    for k in range(0,3):
        for site in range(0,len(sites)):
            A[j,k] = A[j,k] + tmp[site,j] * tmp[site,k]
            
A

array([[ 0.35506615, -0.17231319,  0.01195676],
       [-0.17231319,  0.3499517 ,  0.05159865],
       [ 0.01195676,  0.05159865,  0.0970987 ]])

In [43]:
Ainv = inv(A)
Ainv

array([[ 3.92740726,  2.17559311, -1.63974106],
       [ 2.17559311,  4.30564098, -2.55593856],
       [-1.63974106, -2.55593856, 11.8589539 ]])

In [44]:
 # Hosking and Wallis (1997, eq. 3.3)
D = np.zeros(len(sites))
for site in range(0,len(sites)):
    for j in range(0,3):
        for k in range(0,3):
            D[site] = D[site] + tmp[site,j] * tmp[site,k] * Ainv[j,k]
    
D = D*len(sites)/3.
D

array([4.98494631, 4.07267925, 2.38873216, 1.72129309, 1.60923176,
       1.00552134, 0.92897996, 0.91193096, 0.83781898, 0.73054112,
       0.69160933, 0.63631067, 0.55527354, 0.46044068, 0.37589791,
       0.27871208, 0.27437085, 0.13922961, 0.11807135, 0.1173377 ,
       0.08301818, 0.05554705, 0.02250613])

In [56]:
Dcrit = Dcr_table_31.max()

if len(sites) < 15:
    Dcrit = Dcr_table_31[len(sites)-5]

isD = np.full(len(sites), False, dtype=bool)
for site in range(len(sites)):
    if D[site] > Dcrit:
        isD[site] = True
        
isD

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [54]:
Dcr_table_31[5-5]

1.3333

In [57]:


# Z <- qf(alpha1/nsite, 3, nsite - 4, lower.tail=FALSE)
#  D1.by.Fdist <- (nsite - 1)*Z/(nsite - 4 + 3*Z)

#qf(.95, df1=5, df2=2) 


In [71]:
nsite =len(sites)

In [75]:
V = 0.10/nsite
Z = f.isf(V, 3, nsite-4.)
D1_by_Fdist = (nsite - 1)*Z/(nsite - 4 + 3*Z)
D1_by_Fdist

V = 0.010/nsite
Z = f.isf(V, 3, nsite-4.)
D2_by_Fdist = (nsite - 1)*Z/(nsite - 4 + 3*Z)
D2_by_Fdist

4.430228888173504

In [77]:
signif = []
for site in range(len(sites)):
    if D[site] > D2_by_Fdist:
        signif.append("**")
    elif D[site] > D1_by_Fdist:
        signif.append("*")
    else:
        signif.append("-")

In [78]:
signif

['**',
 '*',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-']